// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Messages {

  /// <summary>Holder for reflection information generated from messages.proto</summary>
  public static partial class MessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5tZXNzYWdlcy5wcm90bxIIbWVzc2FnZXMaEHBsYXllcmluZm8ucHJvdG8a",
            "DnBhdGhpbmZvLnByb3RvGg5yZXNwb25zZS5wcm90byLWAQoLR2FtZU1lc3Nh",
            "Z2USKgoLbWVzc2FnZVR5cGUYASABKA4yFS5tZXNzYWdlcy5NZXNzYWdlVHlw",
            "ZRIyCg1wbGF5ZXJSZXF1ZXN0GAIgASgLMhkucGxheWVyaW5mby5QbGF5ZXJS",
            "ZXF1ZXN0SAASJgoIcmVzcG9uc2UYAyABKAsyEi5tZXNzYWdlcy5SZXNwb25z",
            "ZUgAEjQKDnBsYXllclBvc2l0aW9uGAQgASgLMhoucGxheWVyaW5mby5QbGF5",
            "ZXJQb3NpdGlvbkgAQgkKB21lc3NhZ2UqYgoLTWVzc2FnZVR5cGUSEQoNU0VT",
            "U0lPTl9MT0dJThAAEhIKDlNFU1NJT05fTE9HT1VUEAESEAoMUExBWUVSX1FV",
            "RVJZEAISGgoWUExBWUVSX1BPU0lUSU9OX1VQREFURRADQhJaEHNlcnZlci1n",
            "by9zcmMvcGJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Playerinfo.PlayerinfoReflection.Descriptor, global::Pathinfo.PathinfoReflection.Descriptor, global::Messages.ResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Messages.MessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.GameMessage), global::Messages.GameMessage.Parser, new[]{ "MessageType", "PlayerRequest", "Response", "PlayerPosition" }, new[]{ "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 메시지 타입을 정의
  /// </summary>
  public enum MessageType {
    /// <summary>
    /// 세션 로그인 요청
    /// </summary>
    [pbr::OriginalName("SESSION_LOGIN")] SessionLogin = 0,
    /// <summary>
    /// 세션 로그아웃 요청
    /// </summary>
    [pbr::OriginalName("SESSION_LOGOUT")] SessionLogout = 1,
    /// <summary>
    /// 플레이어 정보 조회 요청
    /// </summary>
    [pbr::OriginalName("PLAYER_QUERY")] PlayerQuery = 2,
    /// <summary>
    /// 플레이어 위치 업데이트 요청
    /// </summary>
    [pbr::OriginalName("PLAYER_POSITION_UPDATE")] PlayerPositionUpdate = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameMessage : pb::IMessage<GameMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameMessage> _parser = new pb::MessageParser<GameMessage>(() => new GameMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.MessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameMessage(GameMessage other) : this() {
      messageType_ = other.messageType_;
      switch (other.MessageCase) {
        case MessageOneofCase.PlayerRequest:
          PlayerRequest = other.PlayerRequest.Clone();
          break;
        case MessageOneofCase.Response:
          Response = other.Response.Clone();
          break;
        case MessageOneofCase.PlayerPosition:
          PlayerPosition = other.PlayerPosition.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameMessage Clone() {
      return new GameMessage(this);
    }

    /// <summary>Field number for the "messageType" field.</summary>
    public const int MessageTypeFieldNumber = 1;
    private global::Messages.MessageType messageType_ = global::Messages.MessageType.SessionLogin;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "playerRequest" field.</summary>
    public const int PlayerRequestFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Playerinfo.PlayerRequest PlayerRequest {
      get { return messageCase_ == MessageOneofCase.PlayerRequest ? (global::Playerinfo.PlayerRequest) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.PlayerRequest;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Response Response {
      get { return messageCase_ == MessageOneofCase.Response ? (global::Messages.Response) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.Response;
      }
    }

    /// <summary>Field number for the "playerPosition" field.</summary>
    public const int PlayerPositionFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Playerinfo.PlayerPosition PlayerPosition {
      get { return messageCase_ == MessageOneofCase.PlayerPosition ? (global::Playerinfo.PlayerPosition) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.PlayerPosition;
      }
    }

    private object message_;
    /// <summary>Enum of possible cases for the "message" oneof.</summary>
    public enum MessageOneofCase {
      None = 0,
      PlayerRequest = 2,
      Response = 3,
      PlayerPosition = 4,
    }
    private MessageOneofCase messageCase_ = MessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageOneofCase MessageCase {
      get { return messageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessage() {
      messageCase_ = MessageOneofCase.None;
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageType != other.MessageType) return false;
      if (!object.Equals(PlayerRequest, other.PlayerRequest)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      if (!object.Equals(PlayerPosition, other.PlayerPosition)) return false;
      if (MessageCase != other.MessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageType != global::Messages.MessageType.SessionLogin) hash ^= MessageType.GetHashCode();
      if (messageCase_ == MessageOneofCase.PlayerRequest) hash ^= PlayerRequest.GetHashCode();
      if (messageCase_ == MessageOneofCase.Response) hash ^= Response.GetHashCode();
      if (messageCase_ == MessageOneofCase.PlayerPosition) hash ^= PlayerPosition.GetHashCode();
      hash ^= (int) messageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageType != global::Messages.MessageType.SessionLogin) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (messageCase_ == MessageOneofCase.PlayerRequest) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayerRequest);
      }
      if (messageCase_ == MessageOneofCase.Response) {
        output.WriteRawTag(26);
        output.WriteMessage(Response);
      }
      if (messageCase_ == MessageOneofCase.PlayerPosition) {
        output.WriteRawTag(34);
        output.WriteMessage(PlayerPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageType != global::Messages.MessageType.SessionLogin) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (messageCase_ == MessageOneofCase.PlayerRequest) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayerRequest);
      }
      if (messageCase_ == MessageOneofCase.Response) {
        output.WriteRawTag(26);
        output.WriteMessage(Response);
      }
      if (messageCase_ == MessageOneofCase.PlayerPosition) {
        output.WriteRawTag(34);
        output.WriteMessage(PlayerPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageType != global::Messages.MessageType.SessionLogin) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (messageCase_ == MessageOneofCase.PlayerRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerRequest);
      }
      if (messageCase_ == MessageOneofCase.Response) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (messageCase_ == MessageOneofCase.PlayerPosition) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerPosition);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameMessage other) {
      if (other == null) {
        return;
      }
      if (other.MessageType != global::Messages.MessageType.SessionLogin) {
        MessageType = other.MessageType;
      }
      switch (other.MessageCase) {
        case MessageOneofCase.PlayerRequest:
          if (PlayerRequest == null) {
            PlayerRequest = new global::Playerinfo.PlayerRequest();
          }
          PlayerRequest.MergeFrom(other.PlayerRequest);
          break;
        case MessageOneofCase.Response:
          if (Response == null) {
            Response = new global::Messages.Response();
          }
          Response.MergeFrom(other.Response);
          break;
        case MessageOneofCase.PlayerPosition:
          if (PlayerPosition == null) {
            PlayerPosition = new global::Playerinfo.PlayerPosition();
          }
          PlayerPosition.MergeFrom(other.PlayerPosition);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageType = (global::Messages.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Playerinfo.PlayerRequest subBuilder = new global::Playerinfo.PlayerRequest();
            if (messageCase_ == MessageOneofCase.PlayerRequest) {
              subBuilder.MergeFrom(PlayerRequest);
            }
            input.ReadMessage(subBuilder);
            PlayerRequest = subBuilder;
            break;
          }
          case 26: {
            global::Messages.Response subBuilder = new global::Messages.Response();
            if (messageCase_ == MessageOneofCase.Response) {
              subBuilder.MergeFrom(Response);
            }
            input.ReadMessage(subBuilder);
            Response = subBuilder;
            break;
          }
          case 34: {
            global::Playerinfo.PlayerPosition subBuilder = new global::Playerinfo.PlayerPosition();
            if (messageCase_ == MessageOneofCase.PlayerPosition) {
              subBuilder.MergeFrom(PlayerPosition);
            }
            input.ReadMessage(subBuilder);
            PlayerPosition = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MessageType = (global::Messages.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Playerinfo.PlayerRequest subBuilder = new global::Playerinfo.PlayerRequest();
            if (messageCase_ == MessageOneofCase.PlayerRequest) {
              subBuilder.MergeFrom(PlayerRequest);
            }
            input.ReadMessage(subBuilder);
            PlayerRequest = subBuilder;
            break;
          }
          case 26: {
            global::Messages.Response subBuilder = new global::Messages.Response();
            if (messageCase_ == MessageOneofCase.Response) {
              subBuilder.MergeFrom(Response);
            }
            input.ReadMessage(subBuilder);
            Response = subBuilder;
            break;
          }
          case 34: {
            global::Playerinfo.PlayerPosition subBuilder = new global::Playerinfo.PlayerPosition();
            if (messageCase_ == MessageOneofCase.PlayerPosition) {
              subBuilder.MergeFrom(PlayerPosition);
            }
            input.ReadMessage(subBuilder);
            PlayerPosition = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
