// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Messages {

  /// <summary>Holder for reflection information generated from messages.proto</summary>
  public static partial class MessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5tZXNzYWdlcy5wcm90bxIIbWVzc2FnZXMaEHBsYXllckluZm8ucHJvdG8a",
            "DnBhdGhJbmZvLnByb3RvGg5yZXNwb25zZS5wcm90bxoOcm9vbUluZm8ucHJv",
            "dG8i+gEKC0dhbWVNZXNzYWdlEioKC21lc3NhZ2VUeXBlGAEgASgOMhUubWVz",
            "c2FnZXMuTWVzc2FnZVR5cGUSLAoKcGxheWVySW5mbxgCIAEoCzIWLnBsYXll",
            "ckluZm8uUGxheWVySW5mb0gAEiYKCHJlc3BvbnNlGAMgASgLMhIubWVzc2Fn",
            "ZXMuUmVzcG9uc2VIABImCghyb29tSW5mbxgEIAEoCzISLnJvb21JbmZvLlJv",
            "b21JbmZvSAASNgoQcm9vbVBsYXllclVwZGF0ZRgFIAEoCzIaLnJvb21JbmZv",
            "LlJvb21QbGF5ZXJVcGRhdGVIAEIJCgdtZXNzYWdlKuQBCgtNZXNzYWdlVHlw",
            "ZRILCgdVTktOT1dOEAASEQoNU0VTU0lPTl9MT0dJThABEhIKDlNFU1NJT05f",
            "TE9HT1VUEAISEAoMUExBWUVSX1FVRVJZEAMSGgoWUExBWUVSX1BPU0lUSU9O",
            "X1VQREFURRAEEhUKEU1BVENITUFLSU5HX1NUQVJUEAUSFgoSTUFUQ0hNQUtJ",
            "TkdfQ0FOQ0VMEAYSFAoQUExBWUVSX0hQX1VQREFURRAHEhgKFFBMQVlFUl9D",
            "SEFOR0VfV0VBUE9OEAgSFAoQUExBWUVSX0FOSU1BVElPThAJQhJaEHNlcnZl",
            "ci1nby9zcmMvcGJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::PlayerInfo.PlayerInfoReflection.Descriptor, global::Pathinfo.PathInfoReflection.Descriptor, global::Messages.ResponseReflection.Descriptor, global::RoomInfo.RoomInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Messages.MessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Messages.GameMessage), global::Messages.GameMessage.Parser, new[]{ "MessageType", "PlayerInfo", "Response", "RoomInfo", "RoomPlayerUpdate" }, new[]{ "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 메시지 타입을 정의
  /// </summary>
  public enum MessageType {
    /// <summary>
    /// 사용안함
    /// </summary>
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    /// 세션 로그인 요청
    /// </summary>
    [pbr::OriginalName("SESSION_LOGIN")] SessionLogin = 1,
    /// <summary>
    /// 세션 로그아웃 요청
    /// </summary>
    [pbr::OriginalName("SESSION_LOGOUT")] SessionLogout = 2,
    /// <summary>
    /// 플레이어 정보 조회 요청
    /// </summary>
    [pbr::OriginalName("PLAYER_QUERY")] PlayerQuery = 3,
    /// <summary>
    /// 플레이어 위치 업데이트 요청
    /// </summary>
    [pbr::OriginalName("PLAYER_POSITION_UPDATE")] PlayerPositionUpdate = 4,
    /// <summary>
    /// 매치 시작
    /// </summary>
    [pbr::OriginalName("MATCHMAKING_START")] MatchmakingStart = 5,
    /// <summary>
    /// 매치 취소
    /// </summary>
    [pbr::OriginalName("MATCHMAKING_CANCEL")] MatchmakingCancel = 6,
    /// <summary>
    /// 플레이어 hp 변경시
    /// </summary>
    [pbr::OriginalName("PLAYER_HP_UPDATE")] PlayerHpUpdate = 7,
    /// <summary>
    /// 플레이어 무기 변경시 요청
    /// </summary>
    [pbr::OriginalName("PLAYER_CHANGE_WEAPON")] PlayerChangeWeapon = 8,
    /// <summary>
    /// 플레이어 애니메이션 파라미터값 변경시
    /// </summary>
    [pbr::OriginalName("PLAYER_ANIMATION")] PlayerAnimation = 9,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 모든 최종 타입은 GameMessage 타입
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameMessage : pb::IMessage<GameMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameMessage> _parser = new pb::MessageParser<GameMessage>(() => new GameMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messages.MessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameMessage(GameMessage other) : this() {
      messageType_ = other.messageType_;
      switch (other.MessageCase) {
        case MessageOneofCase.PlayerInfo:
          PlayerInfo = other.PlayerInfo.Clone();
          break;
        case MessageOneofCase.Response:
          Response = other.Response.Clone();
          break;
        case MessageOneofCase.RoomInfo:
          RoomInfo = other.RoomInfo.Clone();
          break;
        case MessageOneofCase.RoomPlayerUpdate:
          RoomPlayerUpdate = other.RoomPlayerUpdate.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameMessage Clone() {
      return new GameMessage(this);
    }

    /// <summary>Field number for the "messageType" field.</summary>
    public const int MessageTypeFieldNumber = 1;
    private global::Messages.MessageType messageType_ = global::Messages.MessageType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "playerInfo" field.</summary>
    public const int PlayerInfoFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PlayerInfo.PlayerInfo PlayerInfo {
      get { return messageCase_ == MessageOneofCase.PlayerInfo ? (global::PlayerInfo.PlayerInfo) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.PlayerInfo;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messages.Response Response {
      get { return messageCase_ == MessageOneofCase.Response ? (global::Messages.Response) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.Response;
      }
    }

    /// <summary>Field number for the "roomInfo" field.</summary>
    public const int RoomInfoFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RoomInfo.RoomInfo RoomInfo {
      get { return messageCase_ == MessageOneofCase.RoomInfo ? (global::RoomInfo.RoomInfo) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.RoomInfo;
      }
    }

    /// <summary>Field number for the "roomPlayerUpdate" field.</summary>
    public const int RoomPlayerUpdateFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::RoomInfo.RoomPlayerUpdate RoomPlayerUpdate {
      get { return messageCase_ == MessageOneofCase.RoomPlayerUpdate ? (global::RoomInfo.RoomPlayerUpdate) message_ : null; }
      set {
        message_ = value;
        messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.RoomPlayerUpdate;
      }
    }

    private object message_;
    /// <summary>Enum of possible cases for the "message" oneof.</summary>
    public enum MessageOneofCase {
      None = 0,
      PlayerInfo = 2,
      Response = 3,
      RoomInfo = 4,
      RoomPlayerUpdate = 5,
    }
    private MessageOneofCase messageCase_ = MessageOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageOneofCase MessageCase {
      get { return messageCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessage() {
      messageCase_ = MessageOneofCase.None;
      message_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageType != other.MessageType) return false;
      if (!object.Equals(PlayerInfo, other.PlayerInfo)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      if (!object.Equals(RoomInfo, other.RoomInfo)) return false;
      if (!object.Equals(RoomPlayerUpdate, other.RoomPlayerUpdate)) return false;
      if (MessageCase != other.MessageCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageType != global::Messages.MessageType.Unknown) hash ^= MessageType.GetHashCode();
      if (messageCase_ == MessageOneofCase.PlayerInfo) hash ^= PlayerInfo.GetHashCode();
      if (messageCase_ == MessageOneofCase.Response) hash ^= Response.GetHashCode();
      if (messageCase_ == MessageOneofCase.RoomInfo) hash ^= RoomInfo.GetHashCode();
      if (messageCase_ == MessageOneofCase.RoomPlayerUpdate) hash ^= RoomPlayerUpdate.GetHashCode();
      hash ^= (int) messageCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageType != global::Messages.MessageType.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (messageCase_ == MessageOneofCase.PlayerInfo) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayerInfo);
      }
      if (messageCase_ == MessageOneofCase.Response) {
        output.WriteRawTag(26);
        output.WriteMessage(Response);
      }
      if (messageCase_ == MessageOneofCase.RoomInfo) {
        output.WriteRawTag(34);
        output.WriteMessage(RoomInfo);
      }
      if (messageCase_ == MessageOneofCase.RoomPlayerUpdate) {
        output.WriteRawTag(42);
        output.WriteMessage(RoomPlayerUpdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageType != global::Messages.MessageType.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (messageCase_ == MessageOneofCase.PlayerInfo) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayerInfo);
      }
      if (messageCase_ == MessageOneofCase.Response) {
        output.WriteRawTag(26);
        output.WriteMessage(Response);
      }
      if (messageCase_ == MessageOneofCase.RoomInfo) {
        output.WriteRawTag(34);
        output.WriteMessage(RoomInfo);
      }
      if (messageCase_ == MessageOneofCase.RoomPlayerUpdate) {
        output.WriteRawTag(42);
        output.WriteMessage(RoomPlayerUpdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageType != global::Messages.MessageType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (messageCase_ == MessageOneofCase.PlayerInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerInfo);
      }
      if (messageCase_ == MessageOneofCase.Response) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (messageCase_ == MessageOneofCase.RoomInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomInfo);
      }
      if (messageCase_ == MessageOneofCase.RoomPlayerUpdate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomPlayerUpdate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameMessage other) {
      if (other == null) {
        return;
      }
      if (other.MessageType != global::Messages.MessageType.Unknown) {
        MessageType = other.MessageType;
      }
      switch (other.MessageCase) {
        case MessageOneofCase.PlayerInfo:
          if (PlayerInfo == null) {
            PlayerInfo = new global::PlayerInfo.PlayerInfo();
          }
          PlayerInfo.MergeFrom(other.PlayerInfo);
          break;
        case MessageOneofCase.Response:
          if (Response == null) {
            Response = new global::Messages.Response();
          }
          Response.MergeFrom(other.Response);
          break;
        case MessageOneofCase.RoomInfo:
          if (RoomInfo == null) {
            RoomInfo = new global::RoomInfo.RoomInfo();
          }
          RoomInfo.MergeFrom(other.RoomInfo);
          break;
        case MessageOneofCase.RoomPlayerUpdate:
          if (RoomPlayerUpdate == null) {
            RoomPlayerUpdate = new global::RoomInfo.RoomPlayerUpdate();
          }
          RoomPlayerUpdate.MergeFrom(other.RoomPlayerUpdate);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageType = (global::Messages.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            global::PlayerInfo.PlayerInfo subBuilder = new global::PlayerInfo.PlayerInfo();
            if (messageCase_ == MessageOneofCase.PlayerInfo) {
              subBuilder.MergeFrom(PlayerInfo);
            }
            input.ReadMessage(subBuilder);
            PlayerInfo = subBuilder;
            break;
          }
          case 26: {
            global::Messages.Response subBuilder = new global::Messages.Response();
            if (messageCase_ == MessageOneofCase.Response) {
              subBuilder.MergeFrom(Response);
            }
            input.ReadMessage(subBuilder);
            Response = subBuilder;
            break;
          }
          case 34: {
            global::RoomInfo.RoomInfo subBuilder = new global::RoomInfo.RoomInfo();
            if (messageCase_ == MessageOneofCase.RoomInfo) {
              subBuilder.MergeFrom(RoomInfo);
            }
            input.ReadMessage(subBuilder);
            RoomInfo = subBuilder;
            break;
          }
          case 42: {
            global::RoomInfo.RoomPlayerUpdate subBuilder = new global::RoomInfo.RoomPlayerUpdate();
            if (messageCase_ == MessageOneofCase.RoomPlayerUpdate) {
              subBuilder.MergeFrom(RoomPlayerUpdate);
            }
            input.ReadMessage(subBuilder);
            RoomPlayerUpdate = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MessageType = (global::Messages.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            global::PlayerInfo.PlayerInfo subBuilder = new global::PlayerInfo.PlayerInfo();
            if (messageCase_ == MessageOneofCase.PlayerInfo) {
              subBuilder.MergeFrom(PlayerInfo);
            }
            input.ReadMessage(subBuilder);
            PlayerInfo = subBuilder;
            break;
          }
          case 26: {
            global::Messages.Response subBuilder = new global::Messages.Response();
            if (messageCase_ == MessageOneofCase.Response) {
              subBuilder.MergeFrom(Response);
            }
            input.ReadMessage(subBuilder);
            Response = subBuilder;
            break;
          }
          case 34: {
            global::RoomInfo.RoomInfo subBuilder = new global::RoomInfo.RoomInfo();
            if (messageCase_ == MessageOneofCase.RoomInfo) {
              subBuilder.MergeFrom(RoomInfo);
            }
            input.ReadMessage(subBuilder);
            RoomInfo = subBuilder;
            break;
          }
          case 42: {
            global::RoomInfo.RoomPlayerUpdate subBuilder = new global::RoomInfo.RoomPlayerUpdate();
            if (messageCase_ == MessageOneofCase.RoomPlayerUpdate) {
              subBuilder.MergeFrom(RoomPlayerUpdate);
            }
            input.ReadMessage(subBuilder);
            RoomPlayerUpdate = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
